services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Порт для AMQP протокола
      - "15672:15672"  # Порт для веб-интерфейса управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - film-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  film-description-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: film-description-service
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - film-network
    restart: unless-stopped

  # Второй сервис из другого репозитория
  movie_processing_service:
    build:
      context: ../../work/film_processor  # Путь к другому репозиторию (укажите правильный путь)
      dockerfile: Dockerfile
    container_name: movie_processing_service
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - film-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  film-network:
    driver: bridge

