spring.application.name=film_description_service

# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:moviesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# External API Configuration
movie.api.base-url=https://imdb.iamidiotareyoutoo.com/search


# JSON Configuration
spring.jackson.serialization.indent-output=true

# RabbitMQ Configuration
# Используется имя сервиса из docker-compose для работы в контейнерах
# Для локального запуска можно использовать localhost
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
